-- Renomme en français les équipes déjà créées dans des parties existantes (facultatif).
-- Les nouvelles parties utilisent directement les noms français de lib/teamPresets.ts.
begin;
update teams set name = 'Les Anubis' where name = 'Anubis Squad';
update teams set name = 'La Légion des Scarabées' where name = 'Scarab Legion';
update teams set name = 'Les Ailes d’Horus' where name = 'Horus Wings';
update teams set name = 'Les Gardiens du Sphinx' where name = 'Sphinx Guardians';
update teams set name = 'L’Ordre d’Osiris' where name = 'Osiris Order';
update teams set name = 'Le Clan de Bastet' where name = 'Bastet Clan';
update teams set name = 'Les Explorateurs du Nil' where name = 'Nil Explorers';
update teams set name = 'Les Fils de Rê' where name = 'Ra Sunforce';
update teams set name = 'La Dynastie du Cobra' where name = 'Cobra Dynasty';
update teams set name = 'Les Chercheurs de Temples' where name = 'Temple Seekers';
update teams set name = 'Les Novas' where name = 'Team Nova';
update teams set name = 'Les Saturniens' where name = 'Team Saturne';
update teams set name = 'Zénith' where name = 'Zenith';
update teams set name = 'Les Lunaires' where name = 'Team Lune';
update teams set name = 'Les Chevaucheurs d’Étoiles' where name = 'CosmoRiders';
update teams set name = 'Les Nébuleuses' where name = 'Nebula Squad';
update teams set name = 'La Fureur des Jaguars' where name = 'Jaguar Fury';
update teams set name = 'La Tribu des Lianes' where name = 'Tribe Liana';
update teams set name = 'Les Serpents d’Émeraude' where name = 'Emerald Serpent';
update teams set name = 'Les Gardiens du Totem' where name = 'Totem Guardians';
update teams set name = 'Les Perroquets' where name = 'Parrot Squad';
update teams set name = 'Le Clan du Bambou' where name = 'Bamboo Clan';
update teams set name = 'Les Coureurs de Lianes' where name = 'Vine Runners';
update teams set name = 'La Tribu du Singe Solaire' where name = 'Sun Monkey Tribe';
update teams set name = 'Les Esprits de la Jungle' where name = 'Rainforest Spirits';
update teams set name = 'L’Ordre du Crocodile' where name = 'Crocodile Order';
update teams set name = 'Les Grenouilles du Tonnerre' where name = 'Thunder Frog';
update teams set name = 'Les Chasseurs de Fleurs' where name = 'Bloom Hunters';
update teams set name = 'Les Étincelles Quantiques' where name = 'Quantum Sparks';
update teams set name = 'Les Maîtres du Labo' where name = 'Lab Masters';
update teams set name = 'Les Teslas' where name = 'Tesla Squad';
update teams set name = 'La Force Moléculaire' where name = 'Molecule Force';
update teams set name = 'BioGenèse' where name = 'BioGenesis';
update teams set name = 'Les Briseurs de Circuits' where name = 'Circuit Breakers';
update teams set name = 'Les Coureurs de Plasma' where name = 'Plasma Runners';
update teams set name = 'Les Nanobots' where name = 'NanoBots';
update teams set name = 'Le Noyau de Fusion' where name = 'Fusion Core';
update teams set name = 'Les Maîtres de la Gravité' where name = 'Gravity Shift';
update teams set name = 'Tempête Chimique' where name = 'ChemStorm';
update teams set name = 'La Tribu des Photons' where name = 'Photon Tribe';
update teams set name = 'Les Maîtres des Engrenages' where name = 'GearMasters';
update teams set name = 'La Forge à Vapeur' where name = 'SteamForge';
update teams set name = 'Les Coureurs de Boulons' where name = 'BoltRunners';
update teams set name = 'Les Artisans Tesla' where name = 'TeslaCrafters';
update teams set name = 'Les Cerveaux de Cuivre' where name = 'CopperBrains';
update teams set name = 'Les Clés à Molette' where name = 'WrenchSquad';
update teams set name = 'Les Ingénieurs Étincelle' where name = 'SparkEngineers';
update teams set name = 'La Nation des Rouages' where name = 'CogNation';
update teams set name = 'La Tribu des Plans' where name = 'Blueprint Tribe';
update teams set name = 'Les Inventeurs de Fer' where name = 'IronInventors';
update teams set name = 'Les Vapeurbots' where name = 'SteamBots';
update teams set name = 'Les Faiseurs de Temps' where name = 'ChronoMakers';
update teams set name = 'Les Chevaliers du Corail' where name = 'Coral Knights';
update teams set name = 'Les Serpents des Abysses' where name = 'Abyss Serpents';
update teams set name = 'Les Gardiens des Perles' where name = 'Pearl Keepers';
update teams set name = 'Les Gardiens des Marées' where name = 'Tide Guardians';
update teams set name = 'Les Krakens' where name = 'Kraken Squad';
update teams set name = 'La Tribu des Lanternes' where name = 'Sea Lantern Tribe';
update teams set name = 'Les Chevaucheurs de Requins' where name = 'SharkRiders';
update teams set name = 'Les Rangers des Bulles' where name = 'Bubble Rangers';
update teams set name = 'La Force du Trident' where name = 'Trident Force';
update teams set name = 'L’Équipage des Étoiles de Mer' where name = 'Starfish Crew';
update teams set name = 'Le Clan des Coquillages' where name = 'DeepShell Clan';
update teams set name = 'Les Esprits Manta' where name = 'Manta Spirits';
update teams set name = 'Les Flammes du Dragon' where name = 'DragonFlare';
update teams set name = 'Les Feuilles Elfiques' where name = 'ElvenLeaf';
update teams set name = 'Les Mages de Cristal' where name = 'CrystalMages';
update teams set name = 'Les Loups de l’Ombre' where name = 'ShadowWolves';
update teams set name = 'Le Réveil du Phénix' where name = 'PhoenixRise';
update teams set name = 'Les Gardiens des Runes' where name = 'RuneGuardians';
update teams set name = 'La Lumière des Licornes' where name = 'UnicornLight';
update teams set name = 'La Bande des Gobelins' where name = 'GoblinCrew';
update teams set name = 'Les Sorciers de la Lune' where name = 'MoonSorcerers';
update teams set name = 'Les Esprits de la Forêt' where name = 'ForestSpirits';
update teams set name = 'Les Griffons du Tonnerre' where name = 'ThunderGryphons';
update teams set name = 'La Forge Mystique' where name = 'MysticForge';
update teams set name = 'Les Coureurs de Lave' where name = 'LavaRunners';
update teams set name = 'Les Chercheurs de Cristaux' where name = 'CrystalSeekers';
update teams set name = 'Les Gardiens du Magma' where name = 'MagmaGuardians';
update teams set name = 'Le Clan des Stalactites' where name = 'Stalactite Clan';
update teams set name = 'Les Explorateurs des Grottes' where name = 'DeepCave Explorers';
update teams set name = 'La Force des Fossiles' where name = 'FossilForce';
update teams set name = 'La Tribu du Noyau' where name = 'EarthCore Tribe';
update teams set name = 'Les Serpents des Tunnels' where name = 'TunnelSerpents';
update teams set name = 'Les Champignons Lumineux' where name = 'GlowMushrooms';
update teams set name = 'Les Casseurs de Roche' where name = 'RockBreakers';
update teams set name = 'Les Esprits des Géodes' where name = 'Geode Spirits';
update teams set name = 'L’Équipe Souterraine' where name = 'SubterraSquad';
commit;
